[package]
name = "awake-rs"
version = "0.1.0"
authors = ["Segev Finer <segev208@gmail.com>"]
edition = "2021"
rust-version = "1.63"
description = "Keep your computer awake"
license = "MIT"
repository = "https://github.com/segevfiner/awake-rs/"

[dependencies]
cfg-if = "1.0.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.42.0"
features = [
    "Win32_System_Power"
]

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.9.6"
