[package]
name = "awake-rs"
version = "0.1.0"
edition = "2021"
authors = ["Segev Finer <segev208@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies.windows]
version = "0.41.0"
features = [
    "Win32_System_Power"
]
