name: Release

on:
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          target: x86_64-unknown-linux-musl

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cross
        run: cargo install cross

      - name: Build
        run: cross build --verbose --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: keepawake-${{ matrix.target }}
          path: target/${{ matrix.target }}/release
