name: Release

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    strategy:
      matrix:
        include:
        - os: windows-2022
          target: x86_64-pc-windows-msvc
        - os: ubuntu-20.04
          target: x86_64-unknown-linux-musl
        - os: macos-11
          target: x86_64-apple-darwin
        - os: macos-11
          target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cross
        run: cargo install cross

      - name: Install target
        run: rustup target add ${{ matrix.target }}
        if: matrix.target == 'aarch64-apple-darwin'

      - name: Build
        run: cross build --verbose --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v3
        with:
          name: keepawake-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/keepawake
            target/${{ matrix.target }}/release/keepawake.exe
